FROM ubi-minimal

USER root

ENV HOME=/home/deno \
    DENO_INSTALL=/usr/local \
    DENO_DIR=$HOME/.deno \
    PATH=$HOME/.deno/bin:$PATH 

RUN useradd -u 1000 -G wheel, root -d ${HOME} --shell /bin/bash -m deno && \
    #mkdir -p ${HOME}/che /projects && \
    microdnf update && \
    microdnf -y install unzip && \
    curl -fsSL https://deno.land/x/install/install.sh | sh && \
    microdnf clean all && \
    